Home and about pages
AKeeganDev/Capstone_1 pull request #1
Opened 2022-03-09 18:37 UTC by AKeeganDev

2022-03-09 20:00 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED 🔴🟡 🔴 

## Hi @AKeeganDev 👋 

### You are doing a marvelous job on the capstone project and this is one of the best projects I have seen so far!
I really like your presentation for the project 👍

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good accessibility report. ✔️

## Required Changes ♻️
- [ ]  In the presentation video you should show some piece of code that you are very proud of, Please make sure your presentation video includes that.
- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [x]  Please apply the hover effect to your navbar menu links.
- [ ] Please add some screenshots of the project in the readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +        <a href="#">Contact</a>
- [x] Please wrap these links in a list, You can use `ul` list, When we have similar elements it's good practice to wrap them in a list and it also makes sure that our code is semantic.

2022-03-09 20:00 UTC, thecodechaser commented on pages/about.html
> +    <a href="#">Contact</a>
- [x] Please wrap these links in a list, You can use `ul` list, When we have similar elements it's good practice to wrap them in a list and it also makes sure that our code is semantic.

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +            <div id="logo" class="logo"></div>
- [x] Please use anchor tag `<a>` for your logo, Logos are supposed to be links.

2022-03-09 20:00 UTC, thecodechaser commented on css/style.css
> +  .navbar {
- [x] The media queries to apply for the desktop screen should be 768px. Please make sure your styles for desktop screens should start from 768px.

Please see the image below:

![image](https://user-images.githubusercontent.com/83803414/157517664-c2b65fbd-0958-4508-99bc-1472360f772b.png)

2022-03-09 20:00 UTC, thecodechaser commented on css/style.scss
> +  .navbar {
- [x] The media queries to apply for the desktop screen should be 768px. Please make sure your styles for desktop screens should start from 768px.

Please see the image below:

![image](https://user-images.githubusercontent.com/83803414/157517664-c2b65fbd-0958-4508-99bc-1472360f772b.png)

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +            </div>
- [x] Please apply hover effects to your cards, So when we hover over any card it should display a white border around the card

See the below image for reference 

![image](https://user-images.githubusercontent.com/83803414/157519917-a48b8392-e0a4-4d72-a941-4ace3a2afbb9.png)

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +        <a href="#">Contact</a>
- [x] Great job on the navbar menu but there is a little issue. you are supposed to stick to the design as much as possible and your webpage should look identical to the Behance template. You are missing the CC campaign from the menu. Please add that button and make sure it follows the design on the template.

See the image for reference

![image](https://user-images.githubusercontent.com/83803414/157521138-89c9f638-e191-40fc-b172-6e91dd38c43f.png)

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +        <div class="copyright">
- [x] Your design is missing the partner's section before the footer, Please make sure your homepage has the partner section and it should follow the design on the template.

See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/157521779-474e9de1-40a9-4ddb-bc18-990859dbd066.png)

2022-03-09 20:00 UTC, thecodechaser commented on index.html
> +        <div class="copyright">
- [x] Please make sure your footer has a white background color as on the design

See the image for reference

![image](https://user-images.githubusercontent.com/83803414/157522250-562c2113-b656-49e9-aeae-ae2726fb31e2.png)

2022-03-10 01:17 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @AKeeganDev 👋🏻, 

A beautiful job you have done on your capstone project ❤️. 
Also good job on making the requested changes 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 01:17 UTC, Cathella commented on pages/about.html
> +    <a href="../index.html">
- [ ] [OPTIONAL] The file path to the logo can be a `#` or just `index.html` to reference its self

2022-03-10 01:53 UTC, merged